In [1]:
using Revise
using MatrixPolynomials
using LinearAlgebra

## Manipulating polynomials

The first thing to do is to define the variable used, this can be done with the `variable` method.

In [2]:
x = variable("x")

x

Now you can use `x` to create polynomials and perform simple operations.

In [40]:
p1 = x^2+x+1
p2 = x+1
@show p1+p2
@show p1*p2
@time p1^20

p1 + p2 = x²+2x+2
p1 * p2 = x³+2x²+2x+1
  0.000015 seconds (9 allocations: 2.375 KiB)


x⁴⁰+20x³⁹+210x³⁸+1520x³⁷+8455x³⁶+38304x³⁵+146490x³⁴+484500x³³+1409895x³²+3656360x³¹+8533660x³⁰+18062160x²⁹+34880770x²⁸+61757600x²⁷+100640340x²⁶+151419816x²⁵+210859245x²⁴+272290140x²³+326527350x²²+363985680x²¹+377379369x²⁰+363985680x¹⁹+326527350x¹⁸+272290140x¹⁷+210859245x¹⁶+151419816x¹⁵+100640340x¹⁴+61757600x¹³+34880770x¹²+18062160x¹¹+8533660x¹⁰+3656360x⁹+1409895x⁸+484500x⁷+146490x⁶+38304x⁵+8455x⁴+1520x³+210x²+20x+1

 You can also obtain the roots of a polynomial using the `roots` function. Under the hood, this computes the eigenvalues of  the companion matrix

In [42]:
rts = roots(p1)

2-element Array{Complex{Float64},1}:
 -0.49999999999999994 - 0.8660254037844386im
 -0.49999999999999994 + 0.8660254037844386im

In [44]:
subs(p1, rts[2])

1.1102230246251565e-16 + 5.551115123125783e-17im

In [58]:
w1 = wilkinson(20)

x²⁰-210x¹⁹+20615x¹⁸-1256850x¹⁷+53327946x¹⁶-1672280820x¹⁵+40171771630x¹⁴-756111184500x¹³+11310276995381x¹²-135585182899530x¹¹+1307535010540395x¹⁰-10142299865511450x⁹+63030812099294896x⁸-311333643161390640x⁷+1206647803780373360x⁶-3599979517947607200x⁵+8037811822645051776x⁴+5575812828558562816x³-4642984320068847616x²-8752948036761600000x+2432902008176640000

In [60]:
roots(w1)

20-element Array{Complex{Float64},1}:
 -0.9923008314173862 - 5.015979386435323im
 -0.9923008314173862 + 5.015979386435323im
 -0.7889851449338269 - 0.5502464581926152im
 -0.7889851449338269 + 0.5502464581926152im
 0.25728573558269613 + 0.0im
  1.0000000000000093 + 0.0im
  1.6299550165154835 - 8.866884697300247im
  1.6299550165154835 + 8.866884697300247im
    5.80315059108361 - 11.614238602667399im
    5.80315059108361 + 11.614238602667399im
  10.869563214194404 - 12.844373452119767im
  10.869563214194404 + 12.844373452119767im
  16.128220489539114 - 12.36302421903679im
  16.128220489539114 + 12.36302421903679im
  20.871255085482538 - 10.225996023991778im
  20.871255085482538 + 10.225996023991778im
    24.4583395523078 - 6.7265706693493525im
    24.4583395523078 + 6.7265706693493525im
  26.392159159436957 - 2.3433196623813783im
  26.392159159436957 + 2.3433196623813783im

In [65]:
gcd(x+1+eps(), (x+1)^2)

x+1.0000000000000002

In [68]:
y = variable("y", BigInt)

y

In [71]:
typeof(gcd(y+1+eps(), (y+1)^2))

Pol{BigFloat}

In [74]:
x = variable("x")
typeof(x)

x

## Polynomial Matrices

The julia default Array interface is already very powerful and hence a polynomial matrix is just... well, a matrix of polynomials

In [78]:
M = [x^2+x+1 x-1;
     x^2 x]

2×2 Array{Pol{Int64},2}:
 x²+x+1  x-1
 x²      x

In [8]:
deg(M)

2

In [76]:
M1 = [x^2+x+2 x-1;
     x^2 x]
rev(M1)

2×2 Array{Pol{Int64},2}:
 2x²+x+1  -x²+x
 1        x

In [80]:
 A, B = toPencil(M)
A

4×4 Array{Int64,2}:
 -1  -1  -1  1
  0  -1   0  0
  1   0   0  0
  0   1   0  0

## Kronecker canonical form

The package offers several functions to construct the Kronecker canonical form in an easy way

In [81]:
Jcol = colBlock(2)

2×3 Array{Pol{Int64},2}:
 x  -1  0
 0  x   -1

In [82]:
v = [1,x,x^2]

3-element Array{Pol{Int64},1}:
 1
 x
 x²

In [149]:
J0 = zeros(Pol{Int}, 0, 1)

0×1 Array{Pol{Int64},2}

0×1 Array{Pol{Int64},2}

In [84]:
Jcol*v

2-element Array{Pol{Int64},1}:
 0
 0

In [91]:
Jcol = colBlock([1,2,3])

6×9 Array{Pol{Int64},2}:
 x  -1  0  0   0   0  0   0   0
 0  0   x  -1  0   0  0   0   0
 0  0   0  x   -1  0  0   0   0
 0  0   0  0   0   x  -1  0   0
 0  0   0  0   0   0  x   -1  0
 0  0   0  0   0   0  0   x   -1

In [92]:
Jrow = rowBlock([1,2,3])

9×6 Array{Pol{Int64},2}:
 -1  0   0   0   0   0
 x   0   0   0   0   0
 0   -1  0   0   0   0
 0   x   -1  0   0   0
 0   0   x   0   0   0
 0   0   0   -1  0   0
 0   0   0   x   -1  0
 0   0   0   0   x   -1
 0   0   0   0   0   x

In [93]:
Jinf = infBlock([1,2,3])

6×6 Array{Pol{Int64},2}:
 -1  0   0   0   0   0
 0   -1  0   0   0   0
 0   x   -1  0   0   0
 0   0   0   -1  0   0
 0   0   0   x   -1  0
 0   0   0   0   x   -1

In [102]:
J2 = eigBlock(2, [1,3,4])

8×8 Array{Pol{Int64},2}:
 x-2  0    0    0    0    0    0    0
 0    x-2  0    0    0    0    0    0
 0    -1   x-2  0    0    0    0    0
 0    0    -1   x-2  0    0    0    0
 0    0    0    0    x-2  0    0    0
 0    0    0    0    -1   x-2  0    0
 0    0    0    0    0    -1   x-2  0
 0    0    0    0    0    0    -1   x-2

In [103]:
J = blkdiag([Jcol, Jrow, Jinf, J2])

29×29 Array{Pol{Int64},2}:
 x  -1  0  0   0   0  0   0   0   0   …  0    0    0    0    0    0    0
 0  0   x  -1  0   0  0   0   0   0      0    0    0    0    0    0    0
 0  0   0  x   -1  0  0   0   0   0      0    0    0    0    0    0    0
 0  0   0  0   0   x  -1  0   0   0      0    0    0    0    0    0    0
 0  0   0  0   0   0  x   -1  0   0      0    0    0    0    0    0    0
 0  0   0  0   0   0  0   x   -1  0   …  0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   -1     0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   x      0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   0      0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   0      0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   0   …  0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   0      0    0    0    0    0    0    0
 0  0   0  0   0   0  0   0   0   0      0    0    0    0    0    0    0
 ⋮                 ⋮    

In [104]:
A, B = toPencil(J)
ev = eigvals(A, B)  #Av=λBv
filter!(x -> !isnan(x), ev)

18-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  2.0
  2.0
  2.0
  2.0
  2.0
  2.0
  2.0
  2.0
 Inf
 Inf
 Inf
 Inf
 Inf
 Inf

In [105]:
ev = eig(J, 1e-10)
filter!(x -> isfinite(x), ev)
abs.(ev .- 2)

8-element Array{Float64,1}:
 0.00011526176730502013
 0.00011526176730502013
 7.722992184433508e-6
 4.440892098500626e-16
 7.723020392204219e-6
 7.723020392204219e-6
 0.00011526717230910591
 0.00011526717230910591

In [130]:
P = rand(size(J)...)
cond(P)

838.6024523498744

In [131]:
Q = rand(size(J)...)
cond(Q)

466.74467498753063

In [132]:
M = P*J*Q

29×29 Array{Pol{Float64},2}:
 4.929598600310388x-10.663495678046964  …  5.471390496627294x-10.155896099269594
 4.783333676966002x-8.868965231461647      5.4964593967639175x-9.778978006314444
 3.111725835651988x-6.2278796541459505     3.632989317657929x-7.8045497733585
 5.641134862846659x-9.552794741764625      5.532432145429974x-11.848187078323852
 5.328598111643151x-8.89238311969396       6.353752717265315x-10.3448386506665
 4.2084950100544205x-8.862143297144831  …  5.625845190425973x-11.449437226148328
 5.479739773920448x-7.862847668462588      6.617532258362102x-9.809012762557538
 5.901266049875375x-11.720143894616221     6.931127088368667x-13.1505316342036
 5.257283484570026x-9.053089784903817      6.113776220607405x-10.72980457488317
 5.32070646357067x-11.706557516010328      5.1628197119047705x-12.071293170334348
 5.447266353144579x-9.578555115689367   …  5.528109011283805x-11.954792341837294
 4.971113786451572x-5.808784468870957      5.740685638728916x-8.121457907490093
 6.52184

In [116]:
A, B = toPencil(M)

([7.0118588981889545 5.931329907025504 … 6.3863889912507 5.569397109441768; 8.776257750576162 9.51739782977685 … 8.588111195356799 7.65093058358569; … ; 9.132531162381795 8.053970035145504 … 9.880183670126678 8.324030258638192; 9.520198714751729 10.100485291334257 … 11.48210675946616 9.018426846026772], [4.5983309048947305 5.274046029374976 … 4.719925552392399 4.052952904973333; 4.572763105818927 5.535410065626525 … 4.958404658942295 3.7451644376058173; … ; 5.062486379105795 5.7343097905728575 … 6.355166555129728 4.762213020424293; 5.0174183221053505 6.149699151777549 … 6.4769516040371 4.375361571338992])

In [135]:
colIndices(M, 1e-10)
rowIndices(M, 1e-10)
infMultiplicities(M, 1e-10)

3-element Array{Int64,1}:
 1
 2
 3

In [117]:
eigvals(A, B)

29-element Array{Complex{Float64},1}:
                 -Inf + NaN*im
   -57388.95659489477 + 0.0im
  -1.3245519395558192 - 0.21942700325678985im
  -1.3245519395558192 + 0.21942700325678982im
 -0.06487475959677005 + 0.0im
  0.12041025493839383 + 0.0im
  0.16740994269413645 - 0.4630833589885892im
  0.16740994269413645 + 0.4630833589885892im
   0.2604476490881382 - 3.3066562555542838im
   0.2604476490881382 + 3.3066562555542838im
   0.2855858249966718 - 1.0808332281909079im
   0.2855858249966718 + 1.0808332281909077im
   0.8190509523622037 - 0.5670673539502665im
                      ⋮
   1.9997452417558343 + 0.00025432036868571823im
    1.999989070925917 + 1.8938396661033715e-5im
   1.9999890709259172 - 1.8938396661033715e-5im
   1.9999999999997886 + 0.0im
    2.000021858151981 + 0.0im
    2.000254758241422 - 0.0002551965018511543im
    2.000254758241422 + 0.0002551965018511543im
   2.2843820716839196 + 0.0im
    28695.25965981085 - 49700.745211798465im
    28695.25965981085 + 49700.7452

In [119]:
ev = eig(M, 1e-10)

14-element Array{Complex{Float64},1}:
 1.9995593499936966 - 0.00044084881997915346im
 1.9995593499936966 + 0.0004408488199791534im
 1.9999674136270211 - 5.641732236418215e-5im
 1.9999674136270211 + 5.641732236418215e-5im
 2.0000000000000515 + 0.0im
 2.0000651727548524 + 0.0im
 2.0004406500043848 + 0.00044045110343495555im
  2.000440650004385 - 0.00044045110343495555im
                Inf + 0.0im
                Inf + 0.0im
                Inf + 0.0im
                Inf + 0.0im
                Inf + 0.0im
                Inf + 0.0im

In [125]:
filter!(x -> isfinite(x), ev)
abs.(ev .- 2)

8-element Array{Float64,1}:
 0.00062331381352593
 0.00062331381352593
 6.515202196910046e-5
 6.515202196910046e-5
 5.1514348342607263e-14
 6.517275485240503e-5
 0.0006230325841249047
 0.0006230325841252188

In [136]:
M = [x^2 1 0;0 0 0;0 0 x]

3×3 Array{Pol{Int64},2}:
 x²  1  0
 0   0  0
 0   0  x

In [137]:
A, B = toPencil(M)

([0 0 … -1 0; 0 0 … 0 0; … ; 0 1 … 0 0; 0 0 … 0 0], [1 0 … 0 0; 0 0 … 0 0; … ; 0 0 … 1 0; 0 0 … 0 1])

In [138]:
eigvals(A, B)

6-element Array{Float64,1}:
 -Inf
 -Inf
   0.0
  Inf
  Inf
 NaN

In [139]:
ev = eig(M, 1e-10)

2-element Array{Float64,1}:
  0.0
 Inf

In [140]:
colIdx = colIndices(M, 1e-10)

1-element Array{Int64,1}:
 2

In [141]:
rowIdx = rowIndices(M, 1e-10)

1-element Array{Int64,1}:
 0

In [142]:
polrank(M)*deg(M) == sum(colIdx)+sum(rowIdx)+length(ev)

true

In [160]:
M = eigBlock(2, [1,2,3])

6×6 Array{Pol{Int64},2}:
 x-2  0    0    0    0    0
 0    x-2  0    0    0    0
 0    -1   x-2  0    0    0
 0    0    0    x-2  0    0
 0    0    0    -1   x-2  0
 0    0    0    0    -1   x-2

In [161]:
eigMultiplicities(2, M)

3-element Array{Int64,1}:
 1
 2
 3